[project]
name = "data-engineering-ua"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastavro>=1.12.1",
    "flask>=3.1.2",
    "loguru>=0.7.3",
    "requests>=2.32.5",
]
